### ISSUE TITLE
Day 19 문자열, 배열, 조건문

### ISSUE THREAD

**Issue by Irisation23** [bunsung92/Java_Algorithm#25]
# 제목 : 코딩테스트 입문

### 난이도 : Lv.0

> 설명
> - [7의 개수](https://school.programmers.co.kr/learn/courses/30/lessons/120912)
> - [잘라서 배열로 저장하기](https://school.programmers.co.kr/learn/courses/30/lessons/120913)
> - [중복된 숫자 개수](https://school.programmers.co.kr/learn/courses/30/lessons/120583)
> - [머쓱이보다 키 큰 사람](https://school.programmers.co.kr/learn/courses/30/lessons/120585)

**Comment by JoisFe** [comment]
파이팅 !!
